controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


github_check:
    path: /github/check
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController 

connect_google_check:
  path: /connect/google/check
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
